### ISSUE TITLE
Rock radioactivity

### ISSUE THREAD

**Issue by ekneale** [ekneale/CLEANWATCH#3]
The ppm values of rock radioactivity don't look quite right. We should update with new values taken from radiopurity.org for Boulby:
238U: 10 ppm
232Th: 220 ppm
40K: 750 ppm
These values are the worst-case scenario.

**Comment by ekneale** [comment]
Since these values are the radioactivity of the specific isotope, we should take the 'abundance' out of the equation.

**Comment by gayyoda** [comment]
In all Activity functions or just rock?

**Comment by ekneale** [comment]
Good question. Just the rock for the moment until I have checked whether the other values are the radioactivity of natural K or K-40.

**Comment by ekneale** [comment]
Sorry, the values for 238U and 232Th are in ppb.

**Comment by gayyoda** [comment]
ive removed abundance from rock and redefined the values so the unit is ppb instead of ppm
